// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/repository/guest_repository_interface.go

// Package repository is a generated GoMock package.
package repository

import (
	reflect "reflect"

	model "github.com/fpetrikovich/go-guestlist/pkg/model"
	gomock "github.com/golang/mock/gomock"
)

// MockIGuestRepository is a mock of IGuestRepository interface.
type MockIGuestRepository struct {
	ctrl     *gomock.Controller
	recorder *MockIGuestRepositoryMockRecorder
}

// MockIGuestRepositoryMockRecorder is the mock recorder for MockIGuestRepository.
type MockIGuestRepositoryMockRecorder struct {
	mock *MockIGuestRepository
}

// NewMockIGuestRepository creates a new mock instance.
func NewMockIGuestRepository(ctrl *gomock.Controller) *MockIGuestRepository {
	mock := &MockIGuestRepository{ctrl: ctrl}
	mock.recorder = &MockIGuestRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIGuestRepository) EXPECT() *MockIGuestRepositoryMockRecorder {
	return m.recorder
}

// CreateGuest mocks base method.
func (m *MockIGuestRepository) CreateGuest(params *model.GuestData) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateGuest", params)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateGuest indicates an expected call of CreateGuest.
func (mr *MockIGuestRepositoryMockRecorder) CreateGuest(params interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateGuest", reflect.TypeOf((*MockIGuestRepository)(nil).CreateGuest), params)
}

// DeleteGuest mocks base method.
func (m *MockIGuestRepository) DeleteGuest(name string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteGuest", name)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteGuest indicates an expected call of DeleteGuest.
func (mr *MockIGuestRepositoryMockRecorder) DeleteGuest(name interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteGuest", reflect.TypeOf((*MockIGuestRepository)(nil).DeleteGuest), name)
}

// GetArrivedGuests mocks base method.
func (m *MockIGuestRepository) GetArrivedGuests() ([]model.GuestArrival, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetArrivedGuests")
	ret0, _ := ret[0].([]model.GuestArrival)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetArrivedGuests indicates an expected call of GetArrivedGuests.
func (mr *MockIGuestRepositoryMockRecorder) GetArrivedGuests() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetArrivedGuests", reflect.TypeOf((*MockIGuestRepository)(nil).GetArrivedGuests))
}

// GetGuest mocks base method.
func (m *MockIGuestRepository) GetGuest(name string) (*model.Guest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGuest", name)
	ret0, _ := ret[0].(*model.Guest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetGuest indicates an expected call of GetGuest.
func (mr *MockIGuestRepositoryMockRecorder) GetGuest(name interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGuest", reflect.TypeOf((*MockIGuestRepository)(nil).GetGuest), name)
}

// GetGuestList mocks base method.
func (m *MockIGuestRepository) GetGuestList() ([]model.GuestData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGuestList")
	ret0, _ := ret[0].([]model.GuestData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetGuestList indicates an expected call of GetGuestList.
func (mr *MockIGuestRepositoryMockRecorder) GetGuestList() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGuestList", reflect.TypeOf((*MockIGuestRepository)(nil).GetGuestList))
}

// GetGuestTableFreeSeats mocks base method.
func (m *MockIGuestRepository) GetGuestTableFreeSeats(name string) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGuestTableFreeSeats", name)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetGuestTableFreeSeats indicates an expected call of GetGuestTableFreeSeats.
func (mr *MockIGuestRepositoryMockRecorder) GetGuestTableFreeSeats(name interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGuestTableFreeSeats", reflect.TypeOf((*MockIGuestRepository)(nil).GetGuestTableFreeSeats), name)
}

// UpdateGuest mocks base method.
func (m *MockIGuestRepository) UpdateGuest(g *model.Guest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateGuest", g)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateGuest indicates an expected call of UpdateGuest.
func (mr *MockIGuestRepositoryMockRecorder) UpdateGuest(g interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateGuest", reflect.TypeOf((*MockIGuestRepository)(nil).UpdateGuest), g)
}
